server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_PHRASE}
  expired: 10m

spring:
  servlet:
    multipart:
      file-size-threshold: 2048
      max-file-size: 5MB
  application:
    name: tasks_management_system
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  security:
    cors:
      allowedOrigins: ${CORS_ALLOWED_ORIGINS}
      allowedMethods: ${CORS_ALLOWED_METHODS}